default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DB_USER") { ENV['USER'] } %>
  password: <%= ENV.fetch("DB_PASSWORD") { "" } %>
  <% if ENV["DB_HOST"] %>
  host: <%= ENV["DB_HOST"] %>
  <% end %>

development:
  <<: *default
  database: ticket_wave_development

test:
  <<: *default
  database: ticket_wave_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
